version: 0.0.1

phases:
  pre_build:
    commands:
      - echo Instalando pacotes do npm...
      - npm install
  build:
    commands:
      - echo Criando build do projeto...
      - npm run build
  post_build:
    commands:
      - echo Removendo arquivos desnecessários...
      - rm -rf node_modules/

artifacts:
  base-directory: '.'
  files:
    - '**/*'
